# Generated by Django 5.0.4 on 2024-06-10 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_event_end_time_event_init_time_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=250)),
                ('observation', models.CharField(max_length=250)),
                ('deleted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
        ),
    ]
