# Generated by Django 5.0.4 on 2024-06-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='observation',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
