# Generated by Django 5.0.4 on 2024-09-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_workorder_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='diagnosis',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
