# Generated by Django 5.0.4 on 2024-09-13 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_historystatus_prev_end_historystatus_prev_start'),
        ('work_order', '0004_alter_workorder_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='event',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
