# Generated by Django 5.0.4 on 2024-05-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_area_location_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
