# Generated by Django 5.0.4 on 2024-05-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_machine_created_by_machine_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='last_maintenance',
            field=models.DateField(null=True),
        ),
    ]
