# Generated by Django 5.0.4 on 2024-08-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_maintenancetype_maintenancehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancehistory',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='maintenancehistory',
            name='maintenance_type',
        ),
        migrations.RemoveField(
            model_name='maintenancehistory',
            name='performed_by',
        ),
        migrations.DeleteModel(
            name='MaintenanceType',
        ),
        migrations.DeleteModel(
            name='MaintenanceHistory',
        ),
    ]
