# Generated by Django 5.0.4 on 2024-05-04 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('machines', '0003_status_machine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='events.status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='machine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='machines.machine'),
        ),
    ]
