# Generated by Django 5.0.4 on 2024-06-12 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_days', to='events.day'),
        ),
    ]
