# Generated by Django 5.0.4 on 2024-08-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_alter_historystatus_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoIncrementCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counter", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="historystatus",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_status",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="code",
            field=models.CharField(max_length=10),
        ),
    ]
