# Generated by Django 5.0.4 on 2024-08-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_maintenancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancehistory',
            name='maintenance_date',
            field=models.DateTimeField(),
        ),
    ]
