# Generated by Django 5.0.4 on 2024-08-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_maintenancehistory_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='icon',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
