# Generated by Django 5.0.4 on 2024-08-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_status_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancehistory',
            name='event_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
