# Generated by Django 5.0.4 on 2024-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_maintenancehistory_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancehistory',
            name='event_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
