# Generated by Django 5.0.4 on 2024-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_event_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historystatus',
            name='previous_reprogram',
            field=models.BooleanField(default=False),
        ),
    ]
