# Generated by Django 5.0.4 on 2024-08-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_historystatus_previous_reprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='historystatus',
            name='prev_end',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historystatus',
            name='prev_start',
            field=models.DateField(default=None, null=True),
        ),
    ]
