# Generated by Django 5.0.4 on 2024-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_menu_alter_role_name_role_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(related_name='menus', through='roles.Role_Menu', to='roles.menu'),
        ),
    ]
