# Generated by Django 5.0.4 on 2024-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_alter_role_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_menu_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='tooltip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
