# Generated by Django 5.0.4 on 2024-08-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_menu_icon_menu_is_menu_head_menu_link_menu_tooltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='icon',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
