FROM python:3.12.3-slim-bookworm
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app
RUN apt-get update && apt-get install -y \
    libmariadb-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --upgrade pip

COPY ./requirements.txt ./
RUN pip install -r requirements.txt
RUN cd /app
COPY ./ ./
