FROM python:3.12.3-slim-bookworm
WORKDIR /app
RUN apt-get update && apt-get install -y \
    libmariadb-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --upgrade pip

COPY ./requirements.txt ./
RUN pip install -r requirements.txt
RUN cd /app
COPY ./ ./
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
